### ISSUE TITLE
Help with Sakura no Uta

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/EthornellTools#2]
I trying to translate Sakura no uta with custom font to support my language. But there's a problem:
This is a normal scene with the name messing up and the text looks normal
![image](https://user-images.githubusercontent.com/81801486/143465360-dc09994b-d654-4900-9206-a3be22525c94.png)
This is when I save the game 
![image](https://user-images.githubusercontent.com/81801486/143465444-eb14adfd-5b85-43c3-8ed6-3117f31f3c90.png)
And this is when I load it back
![image](https://user-images.githubusercontent.com/81801486/143465483-fe7a0c46-3bba-4dcf-b27a-a85e5d4e632e.png)
I don't know why there are spaces, I'm so confused
This is the text I inserted the game. The game leaves space with only full width character
![image](https://user-images.githubusercontent.com/81801486/143465677-a9458b81-6bec-4cba-8679-f2c577ea7274.png)
At first where I didn't change anything the game leaves space but I after I change **`push 0 to 1`** like in the photo in userdata._bp it doesn't anymore but has problem when saving and loading like I said above
![image](https://user-images.githubusercontent.com/81801486/143466265-fdbf61ac-2ff4-4471-b546-244efddd7bc7.png)

**Comment by arcusmaximus** [comment]
Since the special Vietnamese characters are actually full-width Japanese characters to the game (じ ぢ etc.), I'm guessing it doesn't (always) apply the proportional spacing. Have you tried overriding the half-width katakana characters in your font instead?

**Comment by Cosetto** [comment]
> Since the special Vietnamese characters are actually full-width Japanese characters to the game (じ ぢ etc.), I'm guessing it doesn't (always) apply the proportional spacing. Have you tried overriding the half-width katakana characters in your font instead?

Yes and it's work but doesn't have enough chatacter though, vietnamese has 134 and half width has 63

**Comment by arcusmaximus** [comment]
The game has a bunch of "graphcall 91:88" instructions in msgwndctrl._bp where the second argument from the bottom is hardcoded ("push 0" instead of "load byte"). Try changing these to "push 1" as well - that solves it on my end.

For reference, the offsets are:
0000029F
00000672
000008D1

**Comment by Cosetto** [comment]
> Still doesn't work. Can you check I don't know if I doing anything wrong. 
[サクラノ詩.zip](https://github.com/arcusmaximus/EthornellTools/files/7629936/default.zip)

**Comment by arcusmaximus** [comment]
The .zip only contains ipl._bp. Please patch msgwndctrl._bp instead. You can find it in sysprg.arc.

**Comment by Cosetto** [comment]
[Saku.zip](https://github.com/arcusmaximus/EthornellTools/files/7638067/Saku.zip)
Here again

**Comment by arcusmaximus** [comment]
Works fine for me, even after loading a save...

What you could additionally try is to use this build of [VNTextProxy](https://github.com/arcusmaximus/VNTranslationTools): [dinput8.zip](https://github.com/arcusmaximus/EthornellTools/files/7643843/dinput8.zip)

Just drop it in the game folder. It forces the game to use whatever .ttf (or .otf) file is in the folder - no custom .exe needed.

On a side note, if you use [VNTextPatch](https://github.com/arcusmaximus/VNTranslationTools) to create your translation patch, you don't need to use a custom font at all. Instead you can just type in Vietnamese and have text show up correctly ingame with a regular, unchanged, Vietnamese font.

**Comment by Cosetto** [comment]
![image](https://user-images.githubusercontent.com/81801486/144533995-d529f391-851c-4274-9627-754e6c56e5dc.png)
I ran BGI.exe but still leaves space lol.  Try this"Tôi lặng lẽ nhìn những cánh hoa anh đào chơi vơi lìa cành."

**Comment by arcusmaximus** [comment]
This is what I get, both when starting a new game and when loading:
![image](https://user-images.githubusercontent.com/133129/144642224-1865b2a4-d235-4fc1-b08c-4008d894273b.png)

(Using the Maru.ttf from your previous .zip)

Here are my files:
[Sakuuta.zip](https://github.com/arcusmaximus/EthornellTools/files/7651128/Sakuuta.zip)

**Comment by Cosetto** [comment]
> This is what I get, both when starting a new game and when loading: ![image](https://user-images.githubusercontent.com/133129/144642224-1865b2a4-d235-4fc1-b08c-4008d894273b.png)
> 
> (Using the Maru.ttf from your previous .zip)
> 
> Here are my files: [Sakuuta.zip](https://github.com/arcusmaximus/EthornellTools/files/7651128/Sakuuta.zip)

Ow wow it works what did you change though, and how about the name. Saving is not import the only problem now is the name

**Comment by Cosetto** [comment]
[Sakura no Uta.zip](https://github.com/arcusmaximus/EthornellTools/files/7653074/Sakura.no.Uta.zip)
Here's the first script with name it should show when scene with 2 characters appear, also where can I find the file control font size and words per line, it should be in the msgwndctrl right?
![image](https://user-images.githubusercontent.com/81801486/144691157-5426a109-c591-4f63-8a55-0b1310655184.png)

**Comment by Cosetto** [comment]
So I found way to change the font size, it's in scrmsg but I have to add it  
	**push 5
	mul
	push 6
	div**
There're three places I added: from 000019A2, 000019F9,  00001B5E. You can compare this to the original one
[scrmsg.zip](https://github.com/arcusmaximus/EthornellTools/files/7655941/scrmsg.zip)
I dunno what those lines mean. I found it by comparing with subihibi hd patch. Only name left

**Comment by arcusmaximus** [comment]
The way to change font sizes was already explained in "Notes on Ethornell.txt" in this repository.

Word wrapping can be configured in VNTextPatch.exe.config (settings starting with "ProportionalFontName").

For character names, I found that in this game, they're not rendered in scrmsg._bp but in bitmap._bp. I extended "Notes on Ethornell.txt" with this information.

If you disassemble bitmap._bp, find the "graphcall 92:9C" instruction, and change the 9th push from the bottom (offset 00000F03) from "push 0" to "push 1", character names should show up correctly.

**Comment by arcusmaximus** [comment]
Alternatively, just use this file: [bitmap.zip](https://github.com/arcusmaximus/EthornellTools/files/7677835/bitmap.zip)

**Comment by Cosetto** [comment]
Thanks for your help

**Comment by Cosetto** [comment]
Sorry to bother again but I thought I fixed the log's textbox and name but I just recognize only textbox is fixed
![image](https://user-images.githubusercontent.com/81801486/145346091-0246bb84-d561-41e6-b86c-e6956938d7d3.png)

**Comment by Cosetto** [comment]
In logwnd at offset 0000125B  is the textbox, I tried to change around there but doesn't work

**Comment by arcusmaximus** [comment]
logwnd._bp has a second "graphcall 92:9C" instruction at offset 00001126. If you change the "push 0" at offset 000010CA to "push 1", the name should show up properly as well.

**Comment by Cosetto** [comment]
fixed thanks

**Comment by Cosetto** [comment]
This not really a problem but my friend asked if I can make the log goes in line like this 
![image](https://user-images.githubusercontent.com/81801486/145549726-3e43c617-11df-4050-9f27-0d5ea2f2e60d.png)
But If I put it like that the log can't go over 3 lines. If it isn't in line, it would look like this 
![image](https://user-images.githubusercontent.com/81801486/145549913-4f2d912a-0961-4bd5-87b0-88a2c36848c4.png)
Do you have any idea?

**Comment by Cosetto** [comment]
Here is my log setting
[log.zip](https://github.com/arcusmaximus/EthornellTools/files/7691612/log.zip)

**Comment by arcusmaximus** [comment]
If you want more gray lines in the backlog, you'll need to edit its background image (SGLogWnd990000 in sysgrp.arc). I extended the repository README with tips on how to do this.

**Comment by Cosetto** [comment]
Actually GARbro can convert those too .bmp you need to rename the extension to something like these after extracting then use "Convert multimedia" of GARbro to convert them to .bmp
![image](https://user-images.githubusercontent.com/81801486/145668104-94958127-fe16-42d7-8bd4-253e8ab910a7.png)

**Comment by Cosetto** [comment]
or better way is: double click on sysgrp.arc then **assign** all the files in that as **imagine**, then choose extract all of them as bmp 
![image](https://user-images.githubusercontent.com/81801486/145668282-2c4c0cd2-8d6f-4d51-9d23-91412e498110.png)
![image](https://user-images.githubusercontent.com/81801486/145668294-991106c4-248c-4695-9cd9-553dcc485fcb.png)

**Comment by Cosetto** [comment]
another way is using this https://github.com/xupefei/BGIKit/tree/master/SysgrpConverter, drag and drop the file to the exe it will dump into bmp. After editing drag and drop the bmp to the exe again it will create a new file call .new.bmp, delete the extension then you're done
