### ISSUE TITLE
Does this work with Cho Dengeki Stryker?

### ISSUE THREAD

**Issue by leminhyen2** [arcusmaximus/EthornellTools#3]
I opened what supposedly a script file, for example, 00_00_fuman (with no extension)

It has the string CompressedBG at start.

I typed .\BgiDisassembler.exe .\00_00_fuman

But got this error Unhandled Exception: System.IO.InvalidDataException: Unknown opcode 0x03 encountered at offset 0x00000011

Does that means this program doesn't support the game?

**Comment by Cosetto** [comment]
> 

I think it's a scenario file and this tool doesn't support it. Use hex editor to check if there's Japanese script inside.

**Comment by leminhyen2** [comment]
I did open it with hex editor but the text is encrypted in some ways. Would be nice if there is a solution somehow

**Comment by Cosetto** [comment]
https://github.com/marcussacana/EthornellEditor

**Comment by leminhyen2** [comment]
oh ok, let me try. Do you have an email or discord? I would like to ask some questions about script extraction if you don't mind

**Comment by Cosetto** [comment]
or this https://github.com/mchubby-3rdparty/Bgi_script_tools because I'm using it to translate sakura no uta
![image](https://user-images.githubusercontent.com/81801486/143546898-c0fef439-5399-4ee2-905d-04d736d83ce5.png)

**Comment by leminhyen2** [comment]
thanks, I will check that too

**Comment by leminhyen2** [comment]
I don't know why but both of the repo doesn't work. I'm not sure how to proceed but as the last attempt, I will leave some of the sample scene files here.

If anyone can find a solution to decrypt it, I will be very grateful

https://drive.google.com/file/d/1cuEQjbVPODuz3SntWEsXU-KTtnzE0VWu/view?usp=sharing

**Comment by arcusmaximus** [comment]
As you can see in the README of this repository, files that start with "CompressedBG" are images, not script files.
