### ISSUE TITLE
how to reencode decrypted ._bp files so the engine can read them

### ISSUE THREAD

**Issue by the-math-god** [arcusmaximus/EthornellTools#4]
hi while i love the BgiDisassembler tool but i have no idea how to change the text file back to a ._bp file

**Comment by the-math-god** [comment]
so how do we reassemble the ._bp files exactly

**Comment by arcusmaximus** [comment]
The tool is called "BgiDisassembler". It can't reassemble. If you want to make changes to a ._bp file, you'll need to use a hex editor as shown in the repository's readme.

**Comment by the-math-god** [comment]
ok but the readme is hard to understand could you add instructions with pictures

**Comment by arcusmaximus** [comment]
No, sorry. The tool is meant for people with programming/reverse engineering experience, and for them, the readme should be clear enough as it is.

**Comment by Cosetto** [comment]
@The-Math-God I know this late but try [this](https://github.com/mchubby-3rdparty/Bgi_asdis). bpdis.py is for disassemble by dragging ._bp into it, it will give you .bpd so you can do modify as you want and bpas.py will overwrite old ._bp with new ._bp by dragging .bpd into it. Note that the code is from 6 years ago so the bpop.py maybe missing new opcode from newer games
